image: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/base:0.5"

stages:
  - lint
  - test

.generic:
  variables:
    RUSTFLAGS: -Dwarnings
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - rustc --version && cargo --version

"cargo:test":
  extends: .generic
  stage: test
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/.insteadOf ssh://git@gitlab.com:22/
    - scripts/download-static-libs.sh
    - echo "Running tests without extra features"
    - cargo test --all --features=static --color=always
    - echo "Running tests with instrumentation, benchmark, elastic logging and collector features"
    - cargo test --all --color=always --features=static,instrumentation,benchmark,elastic_logging,collector
    - echo "Running tests with s11n features enabled"
    - cargo test --all --color=always --features=static,s11n_capnp,s11n_serde_cbor
    - echo "Run standard benches"
    - cargo bench --features=static --color=always --no-run

.generic-lint:
  extends: .generic

"lint:fmt":
  extends: .generic-lint
  stage: lint
  image: 192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/base-rust-fmt:2019-11-13
  script:
    - touch src/proto/concordium_p2p_rpc.rs
    - touch src/proto/concordium_p2p_rpc_grpc.rs
    - cargo fmt -- --color=always
    - test $(git ls-files --modified | grep -v ".dll$" | grep -v ".a$" | grep -v ".pc$" | grep -v ".def$" | grep -v "tar.gz" | wc -l) -eq 0 || (echo 'You have introduced some unformatted code:'; git ls-files --modified | grep -v ".dll$" | grep -v ".a$" | grep -v ".pc$" | grep -v ".def$" | grep -v "tar.gz" | sed 's/^/* /'; echo 'Please run `cargo fmt` and amend your MR.'; exit 1)

"lint:clippy":
  extends: .generic-lint
  stage: lint
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/.insteadOf ssh://git@gitlab.com:22/
    - scripts/download-static-libs.sh
    - ( cd deps/internal/consensus/crypto/rust-src && cargo clean )
    - cargo clean
    - echo "Running clippy with without extra features"
    - cargo clippy --color=always --all --features=static -- -Dclippy::all
    - echo "Running clippy with instrumentation, benchmark, elastic logging and collector features"
    - cargo clippy --features=static,instrumentation,benchmark,elastic_logging,collector --color=always --all -- -Dclippy::all
    - echo "Running clippy with s11n extra features enabled"
    - cargo clippy --features=static,s11n_capnp,s11n_serde_cbor --color=always --all -- -Dclippy::all
