image: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/base:0.1"

stages:
  - lint
  - test

.generic:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    RUSTFLAGS: -Dwarnings

"cargo:test":
  extends: .generic
  stage: test
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/.insteadOf ssh://git@gitlab.com:22/
    - rustc --version && cargo --version
    - scripts/download-static-libs.sh
    - ( cd concordium-global-state && cargo test --all --color=always)
    - ( cd concordium-consensus && cargo test --all --color=always --features=static)
    - ( cd concordium-common && cargo test --all --color=always)
    - echo "Running tests without extra features"
    - cargo test --all --features=static --color=always
    - echo "Running tests with instrumentation and benchmark feature enabled"
    - cargo test --all --color=always --features=static,instrumentation,benchmark,elastic_logging
    - echo "Running tests with s11n extras features enabled"
#    - cargo test --all --color=always --features=static,s11n_capnp,s11n_nom,s11n_serde_cbor
    - echo "Run non-serialization benches"
    - cargo bench --features=static --color=always

.generic-lint:
  extends: .generic

"lint:fmt":
  extends: .generic-lint
  stage: lint
  image: rustlang/rust:nightly
  before_script:
    - rustup default nightly-2019-07-25
    - rustup component add rustfmt
  script:
    - rustc --version && cargo --version
    - touch src/proto/concordium_p2p_rpc.rs
    - touch src/proto/concordium_p2p_rpc_grpc.rs
    - cargo fmt -- --color=always
    - ( cd concordium-global-state && cargo fmt -- --color=always)
    - ( cd concordium-consensus && cargo fmt -- --color=always)
    - ( cd concordium-common && cargo fmt -- --color=always)
    - test $(git ls-files --modified | grep -v ".dll$" | grep -v ".a$" | grep -v ".pc$" | grep -v ".def$" | grep -v "tar.gz" | wc -l) -eq 0 || (echo 'You have introduced some unformatted code:'; git ls-files --modified | grep -v ".dll$" | grep -v ".a$" | grep -v ".pc$" | grep -v ".def$" | grep -v "tar.gz" | sed 's/^/* /'; echo 'Please run `cargo fmt` and amend your MR.'; exit 1)

"lint:clippy":
  extends: .generic-lint
  stage: lint
  script:
    - git config --global url.https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/.insteadOf ssh://git@gitlab.com:22/
    - rustc --version && cargo --version
    - scripts/download-static-libs.sh
    - rustup component add clippy
    - ( cd deps/internal/consensus/crypto/rust-src && cargo clean )
    - cargo clean
    - echo "Running clippy with without extra features"
    - cargo clippy --color=always --all --features=static -- -Dclippy::all
    - echo "Running clippy with instrumentation feature enabled"
    - cargo clippy --features=static,instrumentation,benchmark,elastic_logging --color=always --all -- -Dclippy::all
    - echo "Running clippy with s11n extra features enabled"
#    - cargo clippy --features=static,s11n_capnp,s11n_nom,s11n_serde_cbor --color=always --all -- -Dclippy::all