image: "archlinux/base"

test:cargo:
  variables:
    LD_LIBRARY_PATH: "/usr/local/lib"
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - cp scripts/init.build.env.sh .
  - pacman -Sy && pacman -Syyu --noconfirm
  - pacman -S protobuf cmake go clang git libtool rustup make m4 pkgconf autoconf automake file which boost patch libunwind libdwarf elfutils unbound --noconfirm
  - pacman -Scc --noconfirm
  - ./init.build.env.sh
  - rustc --version && cargo --version
  - stack exec -- ghc --print-libdir
  - ( cd dns && cargo test --all --verbose )
  - ( cd consensus-sys && cargo test --all --verbose )
  - cargo test --all --verbose -- --test-threads=1

