image: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/base"

test:cargo:
  script:
  - rustc --version && cargo --version 
  - ( cd ldns-sys && cargo test --all --verbose)
  - cargo test --all --verbose

