image: "rust:latest"

before_script:
  - scripts/init.build.env.sh

test:cargo:
  script:
  - rustc --version && cargo --version 
  - ( cd ldns-sys && cargo test --all --verbose)
  - cargo test --all --verbose

