image: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/base"

test:cargo:
  variables:
    OPENSSL_LIB_DIR: "/usr/lib/openssl-1.0"
    OPENSSL_INCLUDE_DIR: "/usr/include/openssl-1.0"
    LD_LIBRARY_PATH: "/usr/local/lib"
  script:
  - pacman -S openssl-1.0 --noconfirm
  - pacman -S gmp --noconfirm
  - rustc --version && cargo --version
  - ls -lah /root/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/
  - ( cd dns && cargo test --all --verbose )
  - ( cd ldns-sys && cargo test --all --verbose )
  - ( cd consensus-sys && cargo test --all --verbose )
  - cargo test --all --verbose -- --test-threads=1