image: "rust:latest"

before_script:
- echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
- apt-get update -yqq
- apt-get -t stretch-backports install -yqq --no-install-recommends build-essential
- apt-get -t stretch-backports install -y cmake golang-go protobuf-compiler
- git clone https://github.com/mitls/hacl-c
- cd hacl-c
- make
- cp libhacl.so /usr/lib
- cd ..
- ldconfig

test:cargo:
  script:
  - rustup default nightly
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose
