image: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/base"

test:cargo:
  variables:
    LD_LIBRARY_PATH: "/usr/local/lib"
  script:
  - rustc --version && cargo --version
  - stack exec -- ghc --print-libdir
  - ( cd dns && cargo test --all --verbose )
  - ( cd consensus-sys && cargo test --all --verbose )
  - cargo test --all --verbose -- --test-threads=1
