image: "rust:latest"

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential
- git clone https://github.com/mitls/hacl-c
- cd hacl-c
- make
- cp libhacl.so /usr/lib
- cd ..
- ldconfig

test:cargo:
  script:
  - rustup default nightly
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose
