version: '3'
services:
    bootstrapper:
        image: concordium/common:latest
        build: .
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=trace
            - MODE=local_bootstrapper
        entrypoint:
            - /build-project/start.sh
    baker_id_gen:
        image: concordium/common:latest
        entrypoint:
            - /build-project/baker_id_gen
       
    baker:
        image: concordium/common:latest
        depends_on:
            - testrunner
            - baker_id_gen
        entrypoint:
            - /build-project/start.sh
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=debug
            - DESIRED_PEERS=10
            - BOOTSTRAP_NODE=bootstrapper:8888
            - EXTERNAL_PORT=8888
            - NUM_BAKERS=${NUM_BAKERS}
            - MODE=local_basic
        ports:
            - "11100-11500:10000"
    testrunner:
        image: concordium/common:latest
        depends_on:
            - bootstrapper
        entrypoint:
            - /build-project/start.sh
        environment:
            - BOOTSTRAP_NODE=bootstrapper:8888
            - DESIRED_PEERS=${NUM_BAKERS}
            - EXTERNAL_PORT=8888
            - RUST_BACKTRACE=1
            - RUST_LOG=debug
            - MODE=local_testrunner
        ports:
            - "11000:8950"