version: '3'
services:
    receiver:
        image: concordium/common:latest
        depends_on:
            - baker_id_gen
        entrypoint:
            - /build-project/start-tps-test.sh
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=debug
            - DESIRED_PEERS=1
            - EXTERNAL_PORT=8888
            - NUM_BAKERS=${NUM_BAKERS}
            - ID=4000000000000000000000000000000000000000000000000000000000000000
            - TPS_MODE=receiver
    sender:
        image: concordium/common:latest
        depends_on:
            - baker_id_gen
            - receiver
        entrypoint:
            - /build-project/start-tps-test.sh
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=debug
            - DESIRED_PEERS=1
            - EXTERNAL_PORT=8888
            - NUM_BAKERS=${NUM_BAKERS}
            - ID=4000000000000000000000000000000000000000000000000000000000000001
            - TPS_MODE=sender
            - TPS_RECV_ID=4000000000000000000000000000000000000000000000000000000000000000
            - DATA_DIR=/build-project/p2p-client/data

    baker_id_gen:
        image: concordium/common:latest
        entrypoint:
            - /build-project/baker_id_gen