version: '3'
services:
  bootstrapper:
    image: concordium/dev-node:latest
    entrypoint: /bootstrapper-entrypoint.sh
    depends_on:
    - baker_id_gen
    - collector_backend
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - CONCORDIUM_NODE_DATA_DIR=/var/lib/concordium/data
    - CONCORDIUM_NODE_CONFIG_DIR=/var/lib/concordium/config
    - CONCORDIUM_NODE_BOOTSTRAPPER_REGENESIS_BLOCK_HASHES_FILE=/genesis-data/genesis-${NUM_BAKERS}-bakers/genesis_hash
  collector_backend:
    image: concordium/dev-node:latest
    entrypoint: /node-collector-backend
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - COLLECTOR_BACKEND_ADDRESS=0.0.0.0
    - COLLECTOR_BACKEND_PORT=10000
    ports:
    - "12000:10000"
  baker_id_gen:
    image: concordium/dev-node:latest
    entrypoint: /baker_id_generator
  baker:
    image: concordium/dev-node:latest
    depends_on:
    - bootstrapper
    entrypoint: /concordium-node-entrypoint.sh
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - LD_LIBRARY_PATH=/usr/local/lib
    - GENESIS_DATA_PATH=/genesis-data/genesis-${NUM_BAKERS}-bakers
    - BAKER_ID_GEN_NEXT_ID_URL=http://baker_id_gen:8000/next_id
    - CONCORDIUM_NODE_CONNECTION_DESIRED_NODES=${DESIRED_PEERS}
    - CONCORDIUM_NODE_CONNECTION_BOOTSTRAP_NODES=bootstrapper:8888
    - CONCORDIUM_NODE_EXTERNAL_PORT=8888
    - CONCORDIUM_NODE_DATA_DIR=/var/lib/concordium/data
    - CONCORDIUM_NODE_CONFIG_DIR=/var/lib/concordium/config
    - CONCORDIUM_NODE_RPC_SERVER_ADDR=0.0.0.0
    ports:
    - "11100-11500:10000"
  collector:
    image: concordium/dev-node:latest
    entrypoint: /node-collector-entrypoint.sh
    depends_on:
    - baker
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - NUM_BAKERS=${NUM_BAKERS}
    - COLLECTOR_SLEEP=${COLLECTOR_SLEEP}
    - CONCORDIUM_NODE_COLLECTOR_URL=http://collector_backend:10000/nodes/post
