[package]
name = "grpcio"
version = "0.4.0"

[dependencies]
libc = "0.2"
futures = "^0.1.15"
protobuf = { version = "2.0", optional = true }
log = "0.4"

[features]
default = ["protobuf-codec"]
protobuf-codec = ["protobuf"]

