image: "haskell"

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
    LD_LIBRARY_PATH: "${CI_PROJECT_DIR}/crypto/rust-src/target/release:${CI_PROJECT_DIR}/globalstate-mockup/deps/concordium-global-state-sys/target/release:$LD_LIBRARY_PATH"

cache:
  paths:
    - .stack
    - .stack-work
    - target

build-and-test:
  script:
    - "git submodule update --init acorn"
    - "git submodule update --init crypto"
    - "git submodule update --init globalstate-mockup"
    - "cd globalstate-mockup"
    - "git submodule update --init deps/concordium-global-state-sys"
    - "cd deps/concordium-global-state-sys"
    - "git submodule update --init deps/p2p-client"
    - "cd deps/p2p-client"
    - "git submodule update --init deps/internal/consensus"
    - "cd deps/internal/consensus"
    - "git submodule update --init crypto"
    - "cd ${CI_PROJECT_DIR}"
    - "apt-get update && apt-get install -y moreutils curl"
    - "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable"
    - "source $HOME/.cargo/env"
    - "./build-deps.sh"
    - "stack build -v --ghc-options -j4 | ts '[%Y-%m-%d %H:%M:%.S]'"
    - "stack test -v | ts '[%Y-%m-%d %H:%M:%.S]'"
