image: "haskell"

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work
    - target

build-and-test:
  script:
    - "git submodule update --init acorn"
    - "git submodule update --init crypto"
    - "git submodule update --init globalstate-mockup"
    - "cd globalstate-mockup"
    - "git submodule update --init deps/concordium-global-state-sys"
    - "cd deps/concordium-global-state-sys"
    - "git submodule update --init deps/p2p-client"
    - "cd deps/p2p-client"
    - "git submodule update --init deps/internal/crypto"
    - "cd ${CI_PROJECT_DIR}"
    - "apt-get update && apt-get install -y moreutils curl"
    - "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly"
    - "source $HOME/.cargo/env"
    - "./build-deps.sh"
    - "stack build -v --ghc-options -j4 | ts '[%Y-%m-%d %H:%M:%.S]'"
    - "stack test -v | ts '[%Y-%m-%d %H:%M:%.S]'"
