image: "haskell"

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
    GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .stack
    - .stack-work
    - target

build-and-test:
  script:
    - "git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/Concordium/p2p-client.git globalstate-mockup/globalstate/p2p-client"
    - "apt-get update && apt-get install -y moreutils curl"
    - "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly"
    - "source $HOME/.cargo/env"
    - "./build-deps.sh"
    - "stack build -v --ghc-options -j4 | ts '[%Y-%m-%d %H:%M:%.S]'"
    - "stack test -v | ts '[%Y-%m-%d %H:%M:%.S]'"
