image: "haskell:8.6.5"

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack"
    LD_LIBRARY_PATH: "${CI_PROJECT_DIR}/crypto/rust-src/target/release:${CI_PROJECT_DIR}/globalstate-mockup/deps/concordium-global-state-sys/target/release:$LD_LIBRARY_PATH"
    GIT_SUBMODULE_STRATEGY: recursive
cache:
  paths:
    - .stack
    - .stack-work
    - target

build-and-test:
  script:
    - "apt-get update && apt-get install -y moreutils curl"
    - "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable"
    - "source $HOME/.cargo/env"
    - "./build-deps.sh"
    - "stack build -v --ghc-options -j4 | ts '[%Y-%m-%d %H:%M:%.S]'"
    - "stack test -v | ts '[%Y-%m-%d %H:%M:%.S]'"
