resolver: lts-13.21

packages:
- Concordium
- crypto
- acorn
- scheduler
- globalstate-mockup/globalstate-types
- globalstate-mockup/globalstate

extra-deps:
     - QuickCheck-GenT-0.2.0@sha256:d11b7b4a3f7648895eff66376a00f763821ee955ce42a37fb918213a8eae88d6

extra-lib-dirs:
- ./crypto/rust-src/target/release
- ./globalstate-mockup/deps/concordium-global-state-sys/target/release
