[package]
name = "p2p_client"
version = "0.1.57"
description = "Concordium P2P Client"
authors = ["Concordium AG <info@concordium.com>"]
exclude = [".gitignore", ".gitlab-ci.yml", "test/**/*","**/**/.gitignore","**/**/.gitlab-ci.yml"]
publish = false
build = "build.rs"
autobins = false
edition = "2018"
default-run = "p2p_client-cli"
license = "MIT"

[features]
default = []
valgrind = []
s11n_capnp = ["capnp", "capnpc"]
s11n_serde = ["concordium-common/s11n_serde", "serde", "serde_derive"]
s11n_serde_cbor = ["serde_cbor", "s11n_serde"]
s11n_nom = ["nom"]
instrumentation = ["concordium-common/instrumentation", "serde", "serde_derive", "gotham", "mime", "gotham_derive", "hyper", "reqwest"]
benchmark = []
network_dump = []
static = ["concordium-consensus/static"]
profiling = ["concordium-consensus/profiling"]
elastic_logging = [ "elastic", "elastic_derive", "serde_json", "serde/derive", "uuid/v4" ]
collector = [ "reqwest/default-tls", "serde_json", "serde/derive", "gotham", "mime", "gotham_derive", "hyper" ]
beta = [ "serde_json", "serde/derive", "reqwest/default-tls" ]

[dependencies]
# Internal dependencies
concordium-global-state = { path = "concordium-global-state" }
concordium-consensus = { path = "concordium-consensus" }
concordium-dns = { git = "ssh://git@gitlab.com:22/Concordium/rust/concordium-dns.git", branch = "master" }
concordium_crypto_ec_vrf_ed25519_sha256 = { package = "ec_vrf_ed25519_sha256", path = "deps/internal/consensus/crypto/rust-src/ec_vrf_ed25519_sha256" }
concordium_crypto_eddsa_ed25519 = { package = "eddsa_ed25519", path = "deps/internal/consensus/crypto/rust-src/eddsa_ed25519" }
concordium_crypto_sha2 = { package = "sha_2", path = "deps/internal/consensus/crypto/rust-src/sha_2" }
concordium_crypto_elgamal = { package = "elgamal", path = "deps/internal/consensus/crypto/rust-src/elgamal" }
concordium_crypto_pedersen_scheme = { package = "pedersen_scheme", path = "deps/internal/consensus/crypto/rust-src/pedersen_scheme" }
concordium_dodis_yampolskiy_prf = { package = "dodis_yampolskiy_prf", path = "deps/internal/consensus/crypto/rust-src/dodis_yampolskiy_prf" }
# concordium_curve_arithmetic = { package = "curve_arithmetic", path = "deps/internal/consensus/crypto/rust-src/curve_arithmetic" }
concordium-common = { path = "concordium-common" }
# External dependencies
structopt = "0.2"
rand = "^0.6"
hacl-star = "^0.1.0"
mio = "^0.6.19"
log = "0.4"
env_logger = "0.6"
byteorder = "^1.3.2"
preferences = "^1.1.0"
app_dirs2 = "^2.0"
chrono = "0.4"
failure = "^0.1.5"
lazy_static = "^1.2"
human-panic = "1.0"
cfg-if = "0.1"
semver = "0.9"
derive_builder = "0.7.1"
tempfile = "^3.0.7"
base64 = "^0.10.1"
sha2 = "0"
base58check = "^0.1"
rkv = "^0.9"
circular-queue = "^0.2"
# Snow : Noise implementation.
snow = { version = "0.5.2", features = ["hacl-star-accelerated"] }
# gRPC dependencies
protobuf = "2.0.6"
futures = "0.1"
# Feature gated dependencies
gotham = { version = "0.4", optional = true }
gotham_derive = { version = "0.4", optional = true }
hyper = { version = "0.12", optional = true }
reqwest = { version = "^0.9", default-features = false, optional = true }
mime = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["rc"], optional = true }
serde_derive = { version = "1.0", optional = true }
capnp = { version = "^0.9", optional = true }
serde_cbor = { version = "0.9.0", optional = true }
nom = { version = "4.2.0", features = ["verbose-errors"],  optional = true }
hash_hasher = "^2.0"
digest = "0.8.0"
twox-hash = { version = "^1.5.0", features = ["digest"] }
elastic = { version = "0.21.0-pre.5", features = [ "default-tls" ], optional = true }
elastic_derive = { version = "0.21.0-pre.5", optional = true }
serde_json = { version = "1", optional = true }
nohash-hasher = "^0.1"

[target.'cfg(windows)'.dependencies]
ipconfig = { version = "^0.1.9" }
grpciowin = { package = 'grpcio', version = "0.4.0", default-features = false, features = [
  "protobuf-codec"
], path = "deps/windows/grpc-rs-0.4.0" }
grpc = "0.6.1"

[target.'cfg(unix)'.dependencies]
get_if_addrs = { version = "0.5" }
grpciounix = { package = 'grpcio', version = "0.4.4", default-features = false, features = [
  "protobuf-codec"
] }
grpc = "0.6.1"
uuid = { version = "0.7", default-features = false, optional = true }

[build-dependencies]
walkdir = "2"
regex = "1"
protoc-grpcio = "0.2.0"
capnpc = { version = "^0.9", optional = true }

[dev-dependencies]
criterion = "0.2"

[lib]
path = "src/lib.rs"
name = "p2p_client"

[[bin]]
path = "src/bin/block_dump_reader.rs"
name = "read_block_dump"

[[bin]]
path = "src/bin/transaction_reader.rs"
name = "read_transaction"

[[bin]]
path = "src/bin/cli.rs"
name = "p2p_client-cli"

[[bin]]
path = "src/bin/bootstrapper.rs"
name = "p2p_bootstrapper-cli"

[[bin]]
path = "src/bin/dnsrecordgen.rs"
name = "dns_record_generator"

[[bin]]
path = "src/bin/genkey.rs"
name = "dns_key_generator"

[[bin]]
path = "src/bin/generate-new-keypair.rs"
name = "generate-new-keypair"

[[bin]]
name = "node-collector"
path = "src/bin/collector.rs"
required-features = [ "collector" ]

[[bin]]
name = "node-collector-backend"
path = "src/bin/collector_backend.rs"
required-features = [ "collector" ]

[[bench]]
name = "p2p_lib_benchmark"
harness = false
