cargo-features = ["default-run"]

[package]
name = "p2p_client"
version = "0.1.25-debug"
description = "Concordium P2P library"
authors = [ "Concordium AG <info@concordium.com>"]
exclude = [
    ".gitignore",
    ".gitlab-ci.yml",
    "test/**/*"
]
publish = false
build = "build.rs"
default-run = "p2p_client-cli"
autobins = false
edition = "2018"

[features]
default = []
valgrind = []

[dependencies]
libc = "0.2"
structopt = "0.2"
clap = "2"
rand = "^0.6"
rustc-serialize = "^0.3"
hacl-star = "^0.0.14"
mio = "0.6"
bytes = "0.4"
ring = "0.14"
num-bigint = "0.2"
num-traits = "0.2"
log = "0.4"
env_logger = "0.6"
rustls = {version = "0.15", features = [ "dangerous_configuration"]}
time = "0.1"
webpki = "0.19"
byteorder = "1"
untrusted = "0.6.2"
openssl = "0.10"
protobuf        = "2.0.6"
futures         = "0.1"
futures-cpupool = "0.1.8"
tls-api         = "0.1.20"
httpbis         = "^0.7"
preferences = "^1.1.0"
app_dirs = "^1.2.1"
rusqlite = {version = "0.17", features = ["bundled"]}
timer = "0.2"
chrono = "0.4"
arrayref = "0.3"
hex = "0.3"
error-chain = "0.12"
failure = "0.1.5"
iron = "*"
router = "*"
atomic-counter = "^1.0"
lazy_static = "1.2"
human-panic = "1.0"
cfg-if = "0.1"
dns = { path = "dns" }
consensus-sys = { path = "consensus-sys" }
crypto-sys = { path = "crypto-sys" }
hostname = "^0.1"
serde_json = "1.0"
reqwest = { version = "^0.9", default-features = false }
semver = "0.9"
serde = "1.0"
serde_derive = "1.0"
resolv-conf = "0.6"
vecio = "0.1"
derive_builder = "0.7.1"
base64 = "0.10.1"

[target.'cfg(windows)'.dependencies]
ipconfig = { version = "^0.1.9" }
grpciowin          = { package = 'grpcio', version = "0.4.0", default-features = false, features = ["protobuf-codec"], path = "deps/windows/grpc-rs-0.4.0" }
grpc            = "0.5.0"

[target.'cfg(unix)'.dependencies]
get_if_addrs = { version = "0.5" }
grpciounix         = { package = 'grpcio', version = "0.4.0", default-features = false, features = ["protobuf-codec"] }
grpc            = "0.5.0"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
default-features = false
features = ["nightly", "gen", "push", "protobuf"]

[build-dependencies]
walkdir         = "2"
protoc-grpcio   = "0.2.0"

[lib]
path = "src/lib.rs"
name = "p2p_client"

[[bin]]
path = "src/bin/cli.rs"
name = "p2p_client-cli"

[[bin]]
path = "src/bin/bootstrapper.rs"
name = "p2p_bootstrapper-cli"

[[bin]]
path = "src/bin/dnsrecordgen.rs"
name = "dns_record_generator"

[[bin]]
path = "src/bin/genkey.rs"
name = "dns_key_generator"

[[bin]]
path = "src/bin/ipdiscovery.rs"
name = "ip_discovery"

[[bin]]
path = "src/bin/testrunner.rs"
name = "testrunner"

[[bin]]
path = "src/bin/testrunner_parser.rs"
name = "testrunner_parser"

[[bin]]
path = "src/bin/generate-new-keypair.rs"
name = "generate-new-keypair"
