[package]
name = "p2p_client"
version = "0.0.2"
description = "Concordium P2P library"
authors = [ "Ian Johannesen <ij@concordium.com>", "Martin Karlsen Jensen <mkj@concordium.com>"]
exclude = [
    ".gitignore",
    ".gitlab-ci.yml",
    "test/**/*"
]
publish = false
build = "build.rs"

[features]
default = []
valgrind = []

[dependencies]
libc = "0.2"
structopt = "0.2"
clap = "2"
rand = "^0.5"
rustc-serialize = "^0.3"
hacl-star = "^0.0.10"
mio = "0.6"
bytes = "0.4"
ring = "0.13.0-alpha4"
get_if_addrs = "0.5.2"
num-bigint = "0.2"
num-traits = "0.2"
log = "0.4.0"
env_logger = "0.5.10"
rustls = {version = "0.12.0", features = ["logging", "dangerous_configuration"]}
time = "0.1.40"
webpki = "0.18.0-alpha3"
byteorder = "1"
untrusted = "0.6.2"
openssl = "0.10.10"
nom = "^4.0"
protobuf        = "2.0.4"
futures         = "0.1.23"
futures-cpupool = "0.1.8"
tls-api         = "0.1.20"
httpbis         = "0.4.1"
grpcio          = { version = "0.3.0", default-features = false, features = ["protobuf-codec"] } 
grpc            = "0.5.0"
preferences = "^1.1.0"
app_dirs = "^1.2.1"
rusqlite = {version = "0.13.0", features = ["bundled"]}

[build-dependencies]
walkdir         = "2"
protoc-grpcio   = "0.2.0"

[lib]
path = "src/lib.rs"
name = "p2p_client"

[[bin]]
path = "src/main.rs"
name = "p2p_client-cli"