[package]
name = "p2p_client"
version = "0.1.29-debug"
description = "Concordium P2P library"
authors = [ "Concordium AG <info@concordium.com>"]
exclude = [
    ".gitignore",
    ".gitlab-ci.yml",
    "test/**/*"
]
publish = false
build = "build.rs"
autobins = false
edition = "2018"

[features]
default = []
valgrind = []

s11n_capnp = ["capnp", "capnpc" ]
s11n_serde = [ "s11n_serde_cbor", "s11n_serde_json" ]
s11n_serde_json = []
s11n_serde_cbor = ["serde_cbor"]
s11n_nom = ["nom"]

[dependencies]
libc = "0.2"
structopt = "0.2"
rand = "^0.6"
hacl-star = "^0.0.14"
mio = "0.6"
bytes = "0.4"
log = "0.4"
env_logger = "0.6"
rustls = {version = "0.15", features = [ "dangerous_configuration"]}
webpki = "0.19"
byteorder = "1"
openssl = "0.10"
protobuf        = "2.0.6"
futures         = "0.1"
preferences = "^1.1.0"
app_dirs2 = "^2.0"
rusqlite = {version = "0.17", features = ["bundled"]}
chrono = "0.4"
failure = "0.1.5"
iron = "*"
router = "*"
lazy_static = "1.2"
human-panic = "1.0"
cfg-if = "0.1"
dns = { path = "dns" }
consensus-sys = { path = "consensus-sys" }
serde_json = "1.0"
reqwest = { version = "^0.9", default-features = false }
semver = "0.9"
serde = "1.0"
serde_derive = "1.0"
vecio = "0.1"
derive_builder = "0.7.1"
tempfile = "^3.0.7"
base64 = "0.10.1"
sha2 = "0"
base58 = "^0.1"
ec_vrf_ed25519_sha256 = { path = "deps/internal/crypto/rust-src/ec_vrf_ed25519_sha256" }
eddsa_ed25519 = { path = "deps/internal/crypto/rust-src/eddsa_ed25519" }

# Serialization packets are enable as `features`
capnp = { version = "^0.9", optional = true }
serde_cbor = { version = "0.9.0", optional = true }
nom = { version = "4.2.0", optional = true }

[target.'cfg(windows)'.dependencies]
ipconfig = { version = "^0.1.9" }
grpciowin          = { package = 'grpcio', version = "0.4.0", default-features = false, features = ["protobuf-codec"], path = "deps/windows/grpc-rs-0.4.0" }
grpc            = "0.5.0"

[target.'cfg(unix)'.dependencies]
get_if_addrs = { version = "0.5" }
grpciounix         = { package = 'grpcio', version = "0.4.0", default-features = false, features = ["protobuf-codec"] }
grpc            = "0.5.0"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
default-features = false
features = ["gen", "push", "protobuf"]

[build-dependencies]
walkdir         = "2"
protoc-grpcio   = "0.2.0"
capnpc          = { version = "^0.9", optional = true }

[dev-dependencies]
criterion = "0.2"
static_assertions = "^0.3"

[lib]
path = "src/lib.rs"
name = "p2p_client"

[[bin]]
path = "src/bin/cli.rs"
name = "p2p_client-cli"

[[bin]]
path = "src/bin/bootstrapper.rs"
name = "p2p_bootstrapper-cli"

[[bin]]
path = "src/bin/dnsrecordgen.rs"
name = "dns_record_generator"

[[bin]]
path = "src/bin/genkey.rs"
name = "dns_key_generator"

[[bin]]
path = "src/bin/testrunner.rs"
name = "testrunner"

[[bin]]
path = "src/bin/testrunner_parser.rs"
name = "testrunner_parser"

[[bin]]
path = "src/bin/generate-new-keypair.rs"
name = "generate-new-keypair"

[[bench]]
name = "p2p_lib_benchmark"
harness = false
