[package]
name = "p2p_client"
version = "0.0.1"
description = "Rust Coin skel"
authors = [ "Ian Johannesen <ij@nordic-t.me>", "Martin Karlsen Jensen <mj@nordic-t.me>"]
exclude = [
    ".gitignore",
    ".gitlab-ci.yml",
    "test/**/*"
]

[features]
default = []
valgrind = []

[dependencies]
libc = "0.2"
structopt = "0.2"
clap = "2"
rand = "^0.5"
rustc-serialize = "^0.3"
hacl-star = "^0.0.10"
mio = "0.6"
futures = "0.1"
bytes = "0.4"
ring = "0.13.0-alpha4"
get_if_addrs = "0.5.2"
num-bigint = "0.2"
num-traits = "0.2"
log = "0.4.0"
env_logger = "0.5.10"
bincode = "1.0.1"
rustls = {version = "0.12.0", features = ["logging", "dangerous_configuration"]}
time = "0.1.40"
webpki = "0.18.0-alpha3"
untrusted = "0.6.2"
openssl = "0.10.10"

[lib]
path = "src/lib.rs"
name = "p2p_client"

[[bin]]
path = "src/main.rs"
name = "p2p_client-cli"